<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Employees
        $employees = [
            [
                'id' => 1,
                'employee_name' => 'James Mwangi',
                'biometricID' => 'BIO001',
                'employeeID' => 'EMP001',
                'date_of_birth' => '1975-05-15',
                'mobile_no' => '+255712345001',
                'email' => 'james.mwangi@marscomm.co.tz',
                'tin_no' => '123456789',
                'gender' => 'male',
                'marital_status' => 'married',
                'nationality_id' => 1,
                'religion_id' => 1,
                'residential_status' => 'residential',
                'nida_no' => '19750515123456789',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF001',
                'address' => 'Mikocheni, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 6000000.00,
                'advance_option' => true,
                'advance_percentage' => 25.00,
                'paye_exempt' => false,
                'bank_id' => 1,
                'account_no' => '01234567890',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 600000.00,
                'employer_pension_amount' => 600000.00,
                'employee_pension_no' => 'NSSF001234',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 15000.00,
                'overtime_given' => false,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'employee_name' => 'Sarah Kimaro',
                'biometricID' => 'BIO002',
                'employeeID' => 'EMP002',
                'date_of_birth' => '1980-08-22',
                'mobile_no' => '+255712345002',
                'email' => 'sarah.kimaro@marscomm.co.tz',
                'tin_no' => '987654321',
                'gender' => 'female',
                'marital_status' => 'married',
                'nationality_id' => 1,
                'religion_id' => 1,
                'residential_status' => 'residential',
                'nida_no' => '19800822987654321',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF002',
                'address' => 'Masaki, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 3500000.00,
                'advance_option' => true,
                'advance_percentage' => 20.00,
                'paye_exempt' => false,
                'bank_id' => 2,
                'account_no' => '02345678901',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 350000.00,
                'employer_pension_amount' => 350000.00,
                'employee_pension_no' => 'NSSF002345',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 12000.00,
                'overtime_given' => false,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'employee_name' => 'Peter Mushi',
                'biometricID' => 'BIO003',
                'employeeID' => 'EMP003',
                'date_of_birth' => '1985-03-10',
                'mobile_no' => '+255712345003',
                'email' => 'peter.mushi@marscomm.co.tz',
                'tin_no' => '111222333',
                'gender' => 'male',
                'marital_status' => 'single',
                'nationality_id' => 1,
                'religion_id' => 1,
                'residential_status' => 'residential',
                'nida_no' => '19850310111222333',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF003',
                'address' => 'Oyster Bay, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 2000000.00,
                'advance_option' => true,
                'advance_percentage' => 15.00,
                'paye_exempt' => false,
                'bank_id' => 3,
                'account_no' => '03456789012',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 200000.00,
                'employer_pension_amount' => 200000.00,
                'employee_pension_no' => 'NSSF003456',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 10000.00,
                'overtime_given' => true,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'employee_name' => 'Grace Mollel',
                'biometricID' => 'BIO004',
                'employeeID' => 'EMP004',
                'date_of_birth' => '1990-11-30',
                'mobile_no' => '+255712345004',
                'email' => 'grace.mollel@marscomm.co.tz',
                'tin_no' => '444555666',
                'gender' => 'female',
                'marital_status' => 'single',
                'nationality_id' => 1,
                'religion_id' => 1,
                'residential_status' => 'residential',
                'nida_no' => '19901130444555666',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF004',
                'address' => 'Kinondoni, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 1500000.00,
                'advance_option' => true,
                'advance_percentage' => 10.00,
                'paye_exempt' => false,
                'bank_id' => 1,
                'account_no' => '04567890123',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 150000.00,
                'employer_pension_amount' => 150000.00,
                'employee_pension_no' => 'NSSF004567',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 8000.00,
                'overtime_given' => true,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'employee_name' => 'Michael Kasanga',
                'biometricID' => 'BIO005',
                'employeeID' => 'EMP005',
                'date_of_birth' => '1988-07-18',
                'mobile_no' => '+255712345005',
                'email' => 'michael.kasanga@marscomm.co.tz',
                'tin_no' => '777888999',
                'gender' => 'male',
                'marital_status' => 'married',
                'nationality_id' => 1,
                'religion_id' => 2,
                'residential_status' => 'residential',
                'nida_no' => '19880718777888999',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF005',
                'address' => 'Mbezi Beach, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 1300000.00,
                'advance_option' => true,
                'advance_percentage' => 10.00,
                'paye_exempt' => false,
                'bank_id' => 2,
                'account_no' => '05678901234',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 130000.00,
                'employer_pension_amount' => 130000.00,
                'employee_pension_no' => 'NSSF005678',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 8000.00,
                'overtime_given' => true,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'employee_name' => 'Amina Hassan',
                'biometricID' => 'BIO006',
                'employeeID' => 'EMP006',
                'date_of_birth' => '1992-02-14',
                'mobile_no' => '+255712345006',
                'email' => 'amina.hassan@marscomm.co.tz',
                'tin_no' => '222333444',
                'gender' => 'female',
                'marital_status' => 'single',
                'nationality_id' => 1,
                'religion_id' => 2,
                'residential_status' => 'residential',
                'nida_no' => '19920214222333444',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF006',
                'address' => 'Sinza, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 900000.00,
                'advance_option' => false,
                'advance_percentage' => 0.00,
                'paye_exempt' => false,
                'bank_id' => 3,
                'account_no' => '06789012345',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 90000.00,
                'employer_pension_amount' => 90000.00,
                'employee_pension_no' => 'NSSF006789',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 6000.00,
                'overtime_given' => false,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'employee_name' => 'David Lweno',
                'biometricID' => 'BIO007',
                'employeeID' => 'EMP007',
                'date_of_birth' => '1995-09-25',
                'mobile_no' => '+255712345007',
                'email' => 'david.lweno@marscomm.co.tz',
                'tin_no' => '555666777',
                'gender' => 'male',
                'marital_status' => 'single',
                'nationality_id' => 1,
                'religion_id' => 1,
                'residential_status' => 'residential',
                'nida_no' => '19950925555666777',
                'employee_type' => 'Contract',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF007',
                'address' => 'Tegeta, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 600000.00,
                'advance_option' => false,
                'advance_percentage' => 0.00,
                'paye_exempt' => false,
                'bank_id' => 1,
                'account_no' => '07890123456',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 60000.00,
                'employer_pension_amount' => 60000.00,
                'employee_pension_no' => 'NSSF007890',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 5000.00,
                'overtime_given' => true,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'employee_name' => 'Fatuma Juma',
                'biometricID' => 'BIO008',
                'employeeID' => 'EMP008',
                'date_of_birth' => '1993-12-05',
                'mobile_no' => '+255712345008',
                'email' => 'fatuma.juma@marscomm.co.tz',
                'tin_no' => '888999000',
                'gender' => 'female',
                'marital_status' => 'married',
                'nationality_id' => 1,
                'religion_id' => 2,
                'residential_status' => 'residential',
                'nida_no' => '19931205888999000',
                'employee_type' => 'Permanent',
                'employee_status' => 'active',
                'tax_rate_id' => 1,
                'payment_method' => 'bank',
                'wcf_no' => 'WCF008',
                'address' => 'Kawe, Dar es Salaam',
                'company_id' => 1,
                'registration_step' => 'completed',
                'basic_salary' => 700000.00,
                'advance_option' => false,
                'advance_percentage' => 0.00,
                'paye_exempt' => false,
                'bank_id' => 2,
                'account_no' => '08901234567',
                'pension_id' => 1,
                'pension_details' => true,
                'employee_pension_amount' => 70000.00,
                'employer_pension_amount' => 70000.00,
                'employee_pension_no' => 'NSSF008901',
                'nhif' => true,
                'nhif_fixed_amount' => true,
                'nhif_amount' => 5000.00,
                'overtime_given' => false,
                'overtime_rate_weekday' => 1.50,
                'overtime_rate_saturday' => 1.50,
                'overtime_rate_weekend_holiday' => 2.00,
                'use_office_timing' => true,
                'use_biometrics' => true,
                'payments' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('employees')->insert($employees);

        // Employee Departments
        $employeeDepartments = [
            ['employee_id' => 1, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 6, 'jobtitle_id' => 1, 'staff_level_id' => 1, 'joining_date' => '2020-01-15', 'start_date' => '2020-01-15', 'hod' => true, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 2, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 2, 'jobtitle_id' => 5, 'staff_level_id' => 2, 'joining_date' => '2021-03-01', 'start_date' => '2021-03-01', 'hod' => true, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 3, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 3, 'jobtitle_id' => 9, 'staff_level_id' => 3, 'joining_date' => '2022-06-01', 'start_date' => '2022-06-01', 'hod' => true, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 4, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 1, 'jobtitle_id' => 13, 'staff_level_id' => 5, 'joining_date' => '2023-02-15', 'start_date' => '2023-02-15', 'hod' => false, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 5, 'mainstation_id' => 1, 'substation_id' => 2, 'department_id' => 2, 'jobtitle_id' => 14, 'staff_level_id' => 6, 'joining_date' => '2023-05-01', 'start_date' => '2023-05-01', 'hod' => false, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 6, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 6, 'jobtitle_id' => 17, 'staff_level_id' => 6, 'joining_date' => '2023-08-01', 'start_date' => '2023-08-01', 'hod' => false, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 7, 'mainstation_id' => 1, 'substation_id' => 3, 'department_id' => 3, 'jobtitle_id' => 15, 'staff_level_id' => 7, 'joining_date' => '2024-01-10', 'start_date' => '2024-01-10', 'hod' => false, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 8, 'mainstation_id' => 1, 'substation_id' => 1, 'department_id' => 6, 'jobtitle_id' => 18, 'staff_level_id' => 6, 'joining_date' => '2024-03-01', 'start_date' => '2024-03-01', 'hod' => false, 'is_current' => true, 'created_at' => now(), 'updated_at' => now()],
        ];
        DB::table('employee_departments')->insert($employeeDepartments);

        // Employee Earngroups
        $employeeEarngroups = [
            ['employee_id' => 1, 'earngroup_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 2, 'earngroup_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 3, 'earngroup_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 4, 'earngroup_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 5, 'earngroup_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 6, 'earngroup_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 7, 'earngroup_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['employee_id' => 8, 'earngroup_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
        ];
        DB::table('employee_earngroups')->insert($employeeEarngroups);
    }
}

