<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LeaveType;

class LeaveTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $leaveTypes = [
            [
                'leave_type_name' => 'Annual Leave',
                'other_name' => 'Vacation Leave',
                'no_of_days' => 21,
                'no_monthly_increment' => true,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 1.75,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Annual vacation leave for employees',
                'carry_forward' => true,
                'max_carry_forward_days' => 10,
                'requires_approval' => true,
                'requires_documentation' => false,
                'gender_restriction' => 'All',
                'min_service_days' => 0,
            ],
            [
                'leave_type_name' => 'Sick Leave',
                'other_name' => 'Medical Leave',
                'no_of_days' => 14,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Leave for medical reasons and illness',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'All',
                'min_service_days' => 0,
            ],
            [
                'leave_type_name' => 'Maternity Leave',
                'other_name' => 'Maternal Leave',
                'no_of_days' => 90,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Maternity leave for expecting mothers',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'Female',
                'min_service_days' => 180,
            ],
            [
                'leave_type_name' => 'Paternity Leave',
                'other_name' => 'Paternal Leave',
                'no_of_days' => 14,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Paternity leave for new fathers',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'Male',
                'min_service_days' => 90,
            ],
            [
                'leave_type_name' => 'Compassionate Leave',
                'other_name' => 'Bereavement Leave',
                'no_of_days' => 5,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Leave for family emergencies and bereavement',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'All',
                'min_service_days' => 0,
            ],
            [
                'leave_type_name' => 'Study Leave',
                'other_name' => 'Educational Leave',
                'no_of_days' => 30,
                'no_monthly_increment' => false,
                'extra_no_of_days' => true,
                'no_of_monthly_increment' => 0,
                'extra_days' => 15,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Leave for educational purposes and exams',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'All',
                'min_service_days' => 365,
            ],
            [
                'leave_type_name' => 'Emergency Leave',
                'other_name' => 'Urgent Leave',
                'no_of_days' => 3,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Emergency leave for urgent personal matters',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => false,
                'gender_restriction' => 'All',
                'min_service_days' => 0,
            ],
            [
                'leave_type_name' => 'Unpaid Leave',
                'other_name' => 'Leave Without Pay',
                'no_of_days' => 0,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Leave without pay for extended absences',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => true,
                'gender_restriction' => 'All',
                'min_service_days' => 90,
            ],
            [
                'leave_type_name' => 'Personal Leave',
                'other_name' => 'Personal Time Off',
                'no_of_days' => 5,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Personal leave for individual needs',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => false,
                'gender_restriction' => 'All',
                'min_service_days' => 30,
            ],
            [
                'leave_type_name' => 'Religious Leave',
                'other_name' => 'Religious Observance',
                'no_of_days' => 2,
                'no_monthly_increment' => false,
                'extra_no_of_days' => false,
                'no_of_monthly_increment' => 0,
                'extra_days' => 0,
                'show_in_web_portal' => true,
                'status' => 'Active',
                'description' => 'Leave for religious observances and holidays',
                'carry_forward' => false,
                'max_carry_forward_days' => 0,
                'requires_approval' => true,
                'requires_documentation' => false,
                'gender_restriction' => 'All',
                'min_service_days' => 0,
            ]
        ];

        foreach ($leaveTypes as $leaveType) {
            LeaveType::create($leaveType);
        }
    }
}
